#!/usr/bin/env python3
"""Diagnose whether OCR linegrid candidates are a coverage or ranking problem.

This script reads the GT-labeled candidate-action observation cache generated by
``qwen_pair_replace_model.py``.  The GT-derived deltas are used only here for
offline diagnosis; no GT fields are exposed to model prompts or inference-time
pipeline stages.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import Any


PIPE_ROOT = Path(__file__).resolve().parents[1]


def resolve_pipe_path(path: str) -> Path:
    p = Path(path).expanduser()
    if not p.is_absolute():
        p = PIPE_ROOT / p
    return p


def read_json(path: str) -> dict[str, Any]:
    return json.loads(resolve_pipe_path(path).read_text(encoding="utf-8"))


def read_jsonl(path: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with resolve_pipe_path(path).open("r", encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def best_action(rows: list[dict[str, Any]], family: str | None = None) -> dict[str, Any] | None:
    filtered = rows
    if family is not None:
        filtered = [r for r in rows if str(((r.get("candidate") or {}).get("family")) or "") == family]
    if not filtered:
        return None
    return max(filtered, key=lambda r: float(r.get("delta") or 0.0))


def selected_best(rows: list[dict[str, Any]]) -> dict[str, Any] | None:
    selected: list[dict[str, Any]] = []
    for row in rows:
        selected.extend(row.get("selected") or [])
    if not selected:
        return None
    return max(selected, key=lambda r: float(r.get("target_delta") or 0.0))


def summarize(items: list[dict[str, Any]], eps: float) -> dict[str, Any]:
    if not items:
        return {"sample_count": 0}
    return {
        "sample_count": len(items),
        "with_linegrid_actions": sum(1 for x in items if x["linegrid_action_count"] > 0),
        "positive_any_oracle": sum(1 for x in items if x["best_any_delta"] > eps),
        "positive_linegrid_oracle": sum(1 for x in items if x["best_linegrid_delta"] > eps),
        "positive_selected": sum(1 for x in items if x["selected_best_delta"] > eps),
        "missed_positive_linegrid": sum(
            1 for x in items if x["best_linegrid_delta"] > eps and x["selected_best_delta"] <= eps
        ),
        "linegrid_better_than_selected": sum(
            1 for x in items if x["best_linegrid_delta"] > x["selected_best_delta"] + eps
        ),
        "selected_linegrid_samples": sum(1 for x in items if x["selected_has_linegrid"]),
        "mean_base_f1": mean(x["base_f1"] for x in items),
        "mean_best_any_delta": mean(x["best_any_delta"] for x in items),
        "mean_best_linegrid_delta": mean(x["best_linegrid_delta"] for x in items),
        "mean_selected_best_delta": mean(x["selected_best_delta"] for x in items),
        "mean_any_oracle_f1": mean(x["base_f1"] + max(0.0, x["best_any_delta"]) for x in items),
        "mean_linegrid_oracle_f1": mean(x["base_f1"] + max(0.0, x["best_linegrid_delta"]) for x in items),
        "mean_selected_best_f1": mean(x["base_f1"] + max(0.0, x["selected_best_delta"]) for x in items),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-json", required=True)
    parser.add_argument("--eval-json", required=True)
    parser.add_argument("--diag-jsonl", required=True)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--output-jsonl", required=True)
    parser.add_argument("--low-loc-threshold", type=float, default=0.02)
    parser.add_argument("--positive-eps", type=float, default=1e-4)
    parser.add_argument("--top-missed", type=int, default=30)
    args = parser.parse_args()

    cache = read_json(args.cache_json)
    eval_data = read_json(args.eval_json)
    diag_rows = read_jsonl(args.diag_jsonl)
    eval_by_id = {str(s.get("sample_id")): s for s in eval_data.get("samples") or []}
    selected_by_id: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in diag_rows:
        selected_by_id[str(row.get("sample_id"))].append(row)

    obs_by_id: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for obs in cache.get("observations") or []:
        obs_by_id[str(obs.get("sample_id"))].append(obs)

    per_sample: list[dict[str, Any]] = []
    for sid, obs_rows in sorted(obs_by_id.items()):
        sample_eval = eval_by_id.get(sid) or {}
        if sample_eval.get("pred_label") != "FORGED":
            continue
        any_best = best_action(obs_rows)
        linegrid_best = best_action(obs_rows, "linegrid")
        selected = selected_best(selected_by_id.get(sid) or [])
        selected_rows = []
        for row in selected_by_id.get(sid) or []:
            selected_rows.extend(row.get("selected") or [])
        base_f1 = float((any_best or obs_rows[0]).get("base_f1") or 0.0)
        selected_families = {
            str(((r.get("candidate") or {}).get("family")) or "")
            for r in selected_rows
        }
        rec = {
            "sample_id": sid,
            "gt_label": sample_eval.get("gt_label"),
            "pred_label": sample_eval.get("pred_label"),
            "loc_score": float(sample_eval.get("loc_score") or 0.0),
            "lowloc": bool(
                sample_eval.get("gt_label") == "FORGED"
                and sample_eval.get("pred_label") == "FORGED"
                and float(sample_eval.get("loc_score") or 0.0) < args.low_loc_threshold
            ),
            "base_f1": base_f1,
            "action_count": len(obs_rows),
            "linegrid_action_count": sum(
                1 for r in obs_rows if str(((r.get("candidate") or {}).get("family")) or "") == "linegrid"
            ),
            "best_any_delta": float((any_best or {}).get("delta") or 0.0),
            "best_any_family": str((((any_best or {}).get("candidate") or {}).get("family")) or ""),
            "best_any_box": ((any_best or {}).get("candidate") or {}).get("box"),
            "best_linegrid_delta": float((linegrid_best or {}).get("delta") or 0.0),
            "best_linegrid_box": ((linegrid_best or {}).get("candidate") or {}).get("box"),
            "best_linegrid_text": ((linegrid_best or {}).get("candidate") or {}).get("text"),
            "selected_count": len(selected_rows),
            "selected_best_delta": float((selected or {}).get("target_delta") or 0.0),
            "selected_best_family": str((((selected or {}).get("candidate") or {}).get("family")) or ""),
            "selected_has_linegrid": "linegrid" in selected_families,
            "selected_families": sorted(f for f in selected_families if f),
        }
        per_sample.append(rec)

    all_pred = per_sample
    lowloc = [x for x in per_sample if x["lowloc"]]
    gt_forged_pred_forged = [
        x
        for x in per_sample
        if x["gt_label"] == "FORGED" and x["pred_label"] == "FORGED"
    ]
    missed = [
        x
        for x in gt_forged_pred_forged
        if x["best_linegrid_delta"] > args.positive_eps
        and x["selected_best_delta"] <= args.positive_eps
    ]
    missed.sort(key=lambda x: (x["best_linegrid_delta"], -x["loc_score"]), reverse=True)

    out = {
        "cache_json": str(resolve_pipe_path(args.cache_json)),
        "eval_json": str(resolve_pipe_path(args.eval_json)),
        "diag_jsonl": str(resolve_pipe_path(args.diag_jsonl)),
        "low_loc_threshold": args.low_loc_threshold,
        "positive_eps": args.positive_eps,
        "groups": {
            "all_predicted_forged": summarize(all_pred, args.positive_eps),
            "gt_forged_pred_forged": summarize(gt_forged_pred_forged, args.positive_eps),
            "lowloc_gt_forged_pred_forged": summarize(lowloc, args.positive_eps),
        },
        "top_missed_linegrid": missed[: args.top_missed],
    }

    output_json = resolve_pipe_path(args.output_json)
    output_jsonl = resolve_pipe_path(args.output_jsonl)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    with output_jsonl.open("w", encoding="utf-8") as fh:
        for rec in per_sample:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(json.dumps(out["groups"], ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
